apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook-deployment
  labels: # задаем метки
    app: jupyter-notebook
    tier: frontend
spec:
  replicas: 1 # количество реплик
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook # метки, которые будут применены к создаваемым подам
        tier: frontend
    spec:
      containers:
      - name: jupyter-notebook # имя контейнера
        image: my-jupyter-notebook # имя собранного образа Docker для Jupyter Notebook
        imagePullPolicy: Never # явно указываем, что образ не будет загружаться из реестра, а используется локально
        ports:
        - containerPort: 8888 # порт, на котором контейнер будет слушать входящие запросы (стандартный порт для Jupyter Notebook)
        env: # переменные окружения
        - name: JUPYTER_ENABLE_LAB
          valueFrom:
            configMapKeyRef: # ссылка на конфиг-мап
              name: jupyter-postgres-config # имя конфиг-мап
              key: JUPYTER_ENABLE_LAB # ключ в конфиг-мапе
      initContainers: # контейнер-инициализатор
        - name: init-container # имя init-контейнера
          image: alpine:latest # образ для инициализации
          command: ["sh", "-c", "echo 'Initialization complete'"] # команда для инициализации