apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels: # указываем метки
    app: postgres
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        tier: database
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data # путь внутри контейнера, где будет доступен volume
          name: postgres-storage # имя volume, который будет смонтирован в контейнере
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USER -d $POSTGRES_DB -c 'SELECT 1;'"
          initialDelaySeconds: 5
          periodSeconds: 10

      volumes: # создаем volume для пода
      - name: postgres-storage # имя volume, который будет использоваться в контейнерах пода
        persistentVolumeClaim: # ссылка на PersistentVolumeClaim (PVC)
          claimName: postgres-pvc # имя PVC, который будет использоваться для предоставления хранилища